# Generated by Django 4.1.3 on 2022-11-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='+', to='tournaments.team'),
        ),
    ]
