# Generated by Django 4.1.3 on 2022-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_group_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
